services:
  - type: web
    name: my-rails-app
    env: ruby
    buildCommand: |
      bundle install
      bundle exec rake assets:precompile
      bundle exec rake assets:clean
    startCommand: bundle exec puma -C config/puma.rb
    plan: free
    autoDeploy: true
